apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: static-site
      docker:
        dockerfile: Dockerfile
deploy:
  kustomize:
    path: kustomize/overlays/local
portForward:
  - resourceType: service
    resourceName: static-site
    port: 80
    localPort: 3001
profiles:
  - name: native-kubernetes
    deploy:
      kubectl:
        manifests:
          - kubernetes/*

  - name: kustomize-prod
    deploy:
      kustomize:
        path: kustomize/overlays/prod
