apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: service
  name: static-site
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: static-site
  type: NodePort
